### ISSUE TITLE
"run --configure" Invalid input при пропуске необязательных параметров

### ISSUE THREAD

**Issue by MaksimKlepikov** [containerum/chkit#1]
В документации сказано:

> Альтернативный вариант вызова команды chkit run, используя флаг --configure:
> 
> $ chkit run NAME --configure
> Далее необходимо ввести единственный обязательный параметр - имя образа приложения. Все остальные необязательные параметры, описанные выше, будут предложены для ввода в диалоговом режиме, но их можно будет пропустить.

Я запустил комманду chkit run название контейнера --configure
На этапе ввода порта, я ввел 3000. Выдало ошибку Invalid input.
Я решил пропустить этот шаг и нажал enter, но ошибка все равно продолжала вылезать (см. картинку) 
![2017-08-25_11-46-34](https://user-images.githubusercontent.com/9952048/29706708-79520bf8-898b-11e7-8dc7-a8a489cb7fc1.png)

Потом попробовал начать все сначала и сразу же пропустить ввод порта,опять ашипка. Получается параметр порта обязателен и как его вводить не понятно.

**Comment by kfeofantov** [comment]
@kevrat, спасибо что написали. Ошибка проявилась только на винде. Обязательно поправим.

**Comment by xakep666** [comment]
@kevrat проверьте версию 2.0.9
