### ISSUE TITLE
domain manipulations

### ISSUE THREAD

**Issue by Kuznetsov-Ilia** [containerum/chkit#109]
I have some web app, I have a domain picnic.hub.containerum.io and I want to target my domain pucnic.ru to picnic.hub.containerum.io. how can I do it?

**Comment by kfeofantov** [comment]
Hi!

You can use CNAME in your DNS. Or we can add it manually.

For CNAME:
```
RECORD: CNAME
TARGET: picnic.hub.containerum.io
NAME: pucnic.ru
```

You can write me in Telegram: @kfeofantov

**Comment by kfeofantov** [comment]
> Hi!
> 
> 
> You can use CNAME in your DNS. Or we can add it manually.
> 
> For CNAME:
> 
> RECORD: CNAME
> TARGET: picnic.hub.containerum.io
> NAME: pucnic.ru
> 
> You can write me in Telegram: @kfeofantov

**UPD:**
CNAME can use only for *sub-domain*  (ex: *www*).
For add custom domain name, please write us to **support@containerum.io** or **info@containerum.io**
