### ISSUE TITLE
Fix "-n" flag

### ISSUE THREAD

**Issue by testroman1043** [containerum/chkit#137]
Namespace become a default namespace, if we use "-n" flag in request. 

**To Reproduce**
1. ./chkit get default-namespace
2. ./chkit get depl -n %label%
3. ./chkit get default-namespace

**Screenshots**
![screenshot from 2018-06-14 17-57-02](https://user-images.githubusercontent.com/39482891/41420205-9b6aff44-6ffc-11e8-80f2-d7e7ae76e3d9.png)

**Comment by ninedraft** [comment]
fixed
