### ISSUE TITLE
chkit run --commands (-C) not work !

### ISSUE THREAD

**Issue by qxo** [containerum/chkit#29]

**Comment by IvanKhramov** [comment]
@qxo 
Can you describe the problem in more detail?

**Comment by OpsDevil** [comment]
Use the following command:
```chkit run <name> --configure```

**Comment by xakep666** [comment]
fixed by #30

**Comment by IvanKhramov** [comment]
@qxo 
Thanks for reporting the issue, we've fixed it!
Please contact us at support@containerum.io with the e-mail you used to register on Containerum (don't forget to tell us it's you, qxo), and we'll add a small Christmas bonus to your account for your help :)
