### ISSUE TITLE
env managment

### ISSUE THREAD

**Issue by Kuznetsov-Ilia** [containerum/chkit#87]
It is dramatically uncomfortable to define env via web interface and it has ridiculous limit of 35 characters.
I cant find the way to deploy pods from config file using chkit v.3 and cant find where to get chkit v2.0.5 which is described in your tutorial.
You have configmaps - and it is my last hope to get easy way to manage containers with huge env. Pls show me the way how to deal with it)

**Comment by MargoTuleninova** [comment]
Hi!
We're working on chkit v3 tutorial, but it is not currently available. You can define your huge env via chkit interactive mode or using flags. It can be something like this:
`chkit create deploy --image nginx --env KEY0:VALUE0 --env KEY1:VALUE1 -f`
Please, download our latest release to use this feature

**Comment by Kuznetsov-Ilia** [comment]
hm,
```bash
chkit create deploy  \
		--namespace openresty \
		--memory 512 \
		--cpu 500 \
		--replicas 1 \
		--deployment-name testing-env \
		--image nginx \
		--container-name testing-env-0-0-0 \
		--env JWT_SECRET:sOmE-FaKEsEcReTe \
		--env DB_HOST:x2.containerum.io \
		-f
```
creates deployment with wrong env (JWT_SECRET=sOmE; DB_HOST=x2). seems like this [regexp](https://github.com/containerum/chkit/blob/v3.1.1/pkg/util/pairs/pairs.go#L20) does not respect dot and dash (.-) signs
